name: Build application and create release
run-name: ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Platform
        run: sudo apt-get update --fix-missing && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Setup Wails
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Verify Wails
        run: wails3 doctor

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 'v2.x'

      - name: Setup Go Backend
        run: mkdir -p frontend/dist && touch frontend/dist/.gitkeep

      - name: Verify Go Backend
        run: go vet .

      - name: Generate Wails Bindings
        run: wails3 task common:generate:bindings

      - name: Cache Deno Dependencies
        working-directory: ./frontend
        run: deno cache .

      - name: Verify Deno Frontend
        working-directory: ./frontend
        run: deno check .

  build-linux:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Platform
        run: sudo apt-get update --fix-missing && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 'v2.x'

      - name: Setup Wails
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Generate Wails Bindings
        run: wails3 task common:generate:bindings

      - name: Cache Deno Dependencies
        working-directory: ./frontend
        run: deno cache .

      - name: Build for Linux
        run: wails3 task linux:build

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-linux
          path: build/bin/

  build-windows:
    needs: verify
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 'v2.x'

      - name: Setup Wails
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Generate Wails Bindings
        run: wails3 task common:generate:bindings

      - name: Cache Deno Dependencies
        working-directory: ./frontend
        run: deno cache .

      - name: Build for Windows
        run: wails3 task windows:build

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-windows
          path: build/bin/

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Binaries Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./assets
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./assets/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
